//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankEnricher.BankRules {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://rulebase.me.org/", ConfigurationName="BankRules.RuleBaseWS")]
    public interface RuleBaseWS {
        
        // CODEGEN: Generating message contract since element name return from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://rulebase.me.org/RuleBaseWS/rulesRequest", ReplyAction="http://rulebase.me.org/RuleBaseWS/rulesResponse")]
        BankEnricher.BankRules.rulesResponse rules(BankEnricher.BankRules.rulesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rulebase.me.org/RuleBaseWS/rulesRequest", ReplyAction="http://rulebase.me.org/RuleBaseWS/rulesResponse")]
        System.Threading.Tasks.Task<BankEnricher.BankRules.rulesResponse> rulesAsync(BankEnricher.BankRules.rulesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class rulesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="rules", Namespace="http://rulebase.me.org/", Order=0)]
        public BankEnricher.BankRules.rulesRequestBody Body;
        
        public rulesRequest() {
        }
        
        public rulesRequest(BankEnricher.BankRules.rulesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class rulesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float loanduration;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float loanAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int creditScore;
        
        public rulesRequestBody() {
        }
        
        public rulesRequestBody(float loanduration, float loanAmount, int creditScore) {
            this.loanduration = loanduration;
            this.loanAmount = loanAmount;
            this.creditScore = creditScore;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class rulesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="rulesResponse", Namespace="http://rulebase.me.org/", Order=0)]
        public BankEnricher.BankRules.rulesResponseBody Body;
        
        public rulesResponse() {
        }
        
        public rulesResponse(BankEnricher.BankRules.rulesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class rulesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public rulesResponseBody() {
        }
        
        public rulesResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RuleBaseWSChannel : BankEnricher.BankRules.RuleBaseWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RuleBaseWSClient : System.ServiceModel.ClientBase<BankEnricher.BankRules.RuleBaseWS>, BankEnricher.BankRules.RuleBaseWS {
        
        public RuleBaseWSClient() {
        }
        
        public RuleBaseWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RuleBaseWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RuleBaseWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RuleBaseWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankEnricher.BankRules.rulesResponse BankEnricher.BankRules.RuleBaseWS.rules(BankEnricher.BankRules.rulesRequest request) {
            return base.Channel.rules(request);
        }
        
        public string rules(float loanduration, float loanAmount, int creditScore) {
            BankEnricher.BankRules.rulesRequest inValue = new BankEnricher.BankRules.rulesRequest();
            inValue.Body = new BankEnricher.BankRules.rulesRequestBody();
            inValue.Body.loanduration = loanduration;
            inValue.Body.loanAmount = loanAmount;
            inValue.Body.creditScore = creditScore;
            BankEnricher.BankRules.rulesResponse retVal = ((BankEnricher.BankRules.RuleBaseWS)(this)).rules(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankEnricher.BankRules.rulesResponse> BankEnricher.BankRules.RuleBaseWS.rulesAsync(BankEnricher.BankRules.rulesRequest request) {
            return base.Channel.rulesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankEnricher.BankRules.rulesResponse> rulesAsync(float loanduration, float loanAmount, int creditScore) {
            BankEnricher.BankRules.rulesRequest inValue = new BankEnricher.BankRules.rulesRequest();
            inValue.Body = new BankEnricher.BankRules.rulesRequestBody();
            inValue.Body.loanduration = loanduration;
            inValue.Body.loanAmount = loanAmount;
            inValue.Body.creditScore = creditScore;
            return ((BankEnricher.BankRules.RuleBaseWS)(this)).rulesAsync(inValue);
        }
    }
}
