//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankEnricher.Mortens {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bankrulebase.laurbaer.com/", ConfigurationName="Mortens.RuleBase")]
    public interface RuleBase {
        
        // CODEGEN: Generating message contract since element name return from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://bankrulebase.laurbaer.com/RuleBase/rulesRequest", ReplyAction="http://bankrulebase.laurbaer.com/RuleBase/rulesResponse")]
        BankEnricher.Mortens.rulesResponse rules(BankEnricher.Mortens.rulesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bankrulebase.laurbaer.com/RuleBase/rulesRequest", ReplyAction="http://bankrulebase.laurbaer.com/RuleBase/rulesResponse")]
        System.Threading.Tasks.Task<BankEnricher.Mortens.rulesResponse> rulesAsync(BankEnricher.Mortens.rulesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class rulesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="rules", Namespace="http://bankrulebase.laurbaer.com/", Order=0)]
        public BankEnricher.Mortens.rulesRequestBody Body;
        
        public rulesRequest() {
        }
        
        public rulesRequest(BankEnricher.Mortens.rulesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class rulesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float loanduration;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float loanAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int creditScore;
        
        public rulesRequestBody() {
        }
        
        public rulesRequestBody(float loanduration, float loanAmount, int creditScore) {
            this.loanduration = loanduration;
            this.loanAmount = loanAmount;
            this.creditScore = creditScore;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class rulesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="rulesResponse", Namespace="http://bankrulebase.laurbaer.com/", Order=0)]
        public BankEnricher.Mortens.rulesResponseBody Body;
        
        public rulesResponse() {
        }
        
        public rulesResponse(BankEnricher.Mortens.rulesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class rulesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public rulesResponseBody() {
        }
        
        public rulesResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RuleBaseChannel : BankEnricher.Mortens.RuleBase, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RuleBaseClient : System.ServiceModel.ClientBase<BankEnricher.Mortens.RuleBase>, BankEnricher.Mortens.RuleBase {
        
        public RuleBaseClient() {
        }
        
        public RuleBaseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RuleBaseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RuleBaseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RuleBaseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankEnricher.Mortens.rulesResponse BankEnricher.Mortens.RuleBase.rules(BankEnricher.Mortens.rulesRequest request) {
            return base.Channel.rules(request);
        }
        
        public string rules(float loanduration, float loanAmount, int creditScore) {
            BankEnricher.Mortens.rulesRequest inValue = new BankEnricher.Mortens.rulesRequest();
            inValue.Body = new BankEnricher.Mortens.rulesRequestBody();
            inValue.Body.loanduration = loanduration;
            inValue.Body.loanAmount = loanAmount;
            inValue.Body.creditScore = creditScore;
            BankEnricher.Mortens.rulesResponse retVal = ((BankEnricher.Mortens.RuleBase)(this)).rules(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankEnricher.Mortens.rulesResponse> BankEnricher.Mortens.RuleBase.rulesAsync(BankEnricher.Mortens.rulesRequest request) {
            return base.Channel.rulesAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankEnricher.Mortens.rulesResponse> rulesAsync(float loanduration, float loanAmount, int creditScore) {
            BankEnricher.Mortens.rulesRequest inValue = new BankEnricher.Mortens.rulesRequest();
            inValue.Body = new BankEnricher.Mortens.rulesRequestBody();
            inValue.Body.loanduration = loanduration;
            inValue.Body.loanAmount = loanAmount;
            inValue.Body.creditScore = creditScore;
            return ((BankEnricher.Mortens.RuleBase)(this)).rulesAsync(inValue);
        }
    }
}
