//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="laurbaer_namespace", ConfigurationName="ServiceReference1.LaurbaerServiceSoap")]
    public interface LaurbaerServiceSoap {
        
        // CODEGEN: Generating message contract since element name ssn from namespace laurbaer_namespace is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="laurbaer_namespace/SoapLoanRequest", ReplyAction="*")]
        SoapClient.ServiceReference1.SoapLoanRequestResponse SoapLoanRequest(SoapClient.ServiceReference1.SoapLoanRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="laurbaer_namespace/SoapLoanRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapClient.ServiceReference1.SoapLoanRequestResponse> SoapLoanRequestAsync(SoapClient.ServiceReference1.SoapLoanRequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoapLoanRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SoapLoanRequest", Namespace="laurbaer_namespace", Order=0)]
        public SoapClient.ServiceReference1.SoapLoanRequestRequestBody Body;
        
        public SoapLoanRequestRequest() {
        }
        
        public SoapLoanRequestRequest(SoapClient.ServiceReference1.SoapLoanRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="laurbaer_namespace")]
    public partial class SoapLoanRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ssn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float loanAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public float loanDuration;
        
        public SoapLoanRequestRequestBody() {
        }
        
        public SoapLoanRequestRequestBody(string ssn, float loanAmount, float loanDuration) {
            this.ssn = ssn;
            this.loanAmount = loanAmount;
            this.loanDuration = loanDuration;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoapLoanRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SoapLoanRequestResponse", Namespace="laurbaer_namespace", Order=0)]
        public SoapClient.ServiceReference1.SoapLoanRequestResponseBody Body;
        
        public SoapLoanRequestResponse() {
        }
        
        public SoapLoanRequestResponse(SoapClient.ServiceReference1.SoapLoanRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="laurbaer_namespace")]
    public partial class SoapLoanRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SoapLoanRequestResult;
        
        public SoapLoanRequestResponseBody() {
        }
        
        public SoapLoanRequestResponseBody(string SoapLoanRequestResult) {
            this.SoapLoanRequestResult = SoapLoanRequestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LaurbaerServiceSoapChannel : SoapClient.ServiceReference1.LaurbaerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LaurbaerServiceSoapClient : System.ServiceModel.ClientBase<SoapClient.ServiceReference1.LaurbaerServiceSoap>, SoapClient.ServiceReference1.LaurbaerServiceSoap {
        
        public LaurbaerServiceSoapClient() {
        }
        
        public LaurbaerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LaurbaerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LaurbaerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LaurbaerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapClient.ServiceReference1.SoapLoanRequestResponse SoapClient.ServiceReference1.LaurbaerServiceSoap.SoapLoanRequest(SoapClient.ServiceReference1.SoapLoanRequestRequest request) {
            return base.Channel.SoapLoanRequest(request);
        }
        
        public string SoapLoanRequest(string ssn, float loanAmount, float loanDuration) {
            SoapClient.ServiceReference1.SoapLoanRequestRequest inValue = new SoapClient.ServiceReference1.SoapLoanRequestRequest();
            inValue.Body = new SoapClient.ServiceReference1.SoapLoanRequestRequestBody();
            inValue.Body.ssn = ssn;
            inValue.Body.loanAmount = loanAmount;
            inValue.Body.loanDuration = loanDuration;
            SoapClient.ServiceReference1.SoapLoanRequestResponse retVal = ((SoapClient.ServiceReference1.LaurbaerServiceSoap)(this)).SoapLoanRequest(inValue);
            return retVal.Body.SoapLoanRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapClient.ServiceReference1.SoapLoanRequestResponse> SoapClient.ServiceReference1.LaurbaerServiceSoap.SoapLoanRequestAsync(SoapClient.ServiceReference1.SoapLoanRequestRequest request) {
            return base.Channel.SoapLoanRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapClient.ServiceReference1.SoapLoanRequestResponse> SoapLoanRequestAsync(string ssn, float loanAmount, float loanDuration) {
            SoapClient.ServiceReference1.SoapLoanRequestRequest inValue = new SoapClient.ServiceReference1.SoapLoanRequestRequest();
            inValue.Body = new SoapClient.ServiceReference1.SoapLoanRequestRequestBody();
            inValue.Body.ssn = ssn;
            inValue.Body.loanAmount = loanAmount;
            inValue.Body.loanDuration = loanDuration;
            return ((SoapClient.ServiceReference1.LaurbaerServiceSoap)(this)).SoapLoanRequestAsync(inValue);
        }
    }
}
